# Generated by Django 4.1.4 on 2023-01-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_tweet_all_comments_comments_tweet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='tweet',
        ),
        migrations.AddField(
            model_name='tweet',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='base.comments'),
        ),
    ]
