# Generated by Django 4.1.4 on 2023-01-26 19:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_tweet_likes_remove_tweet_retweets_retweets'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_followers',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_following',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
