# Generated by Django 4.1.4 on 2023-01-26 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_customuser_user_followers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollowing',
            old_name='user_id',
            new_name='user_who_is_following',
        ),
        migrations.RenameField(
            model_name='userfollowing',
            old_name='following_user_id',
            new_name='user_who_is_getting_followed',
        ),
    ]
